spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/test
    password: ''
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none